### PR TITLE
Proper setup of travis & rubocop, formatting fixes

### PR DESCRIPTION
**Pull request by stefanhorning**
(Auto)corrected some formatting through rubocop and simplified rubocop rule exception configurations.

Fixed setup script to work with default postgres user on Ubuntu boxes.

### CODE REVIEW

**Comment by radiospiel** [comment]
Stefan, thanks for looking into this.

However, this PR cannot be merged as of now.

- bin/release must be moved back into ./scripts. Reason: ./bin should not contain stuff that someone else might think is an exported binary of this gem
- the RC fixes are questionable. At least the ones in queue.rb must go, since there is a branch which heavily adjusts it. Please revert at least queue.rb back to where it was before.

**Comment by stefanhorning** [comment]
But with that logic everything except `bin/postjob` (and maybe bin console) should be moved to `scripts/`, right?

**Comment by radiospiel** [comment]
I mean all the other stuff is from rubocop, is it not? In any case, lets look at this together on monday

**Comment by stefanhorning** [comment]
Now made it so that `bin/` contains only binstubs (as it already did contain some before) and `scripts/` the rest (`release` and `setup`).

If you want to introduce a new logic of "only exported binaries of this gem should go to bin/" you can still do that lateron, but I wouldn't do it as part of this PR. The objective here was only to make a build on travis work.

**Comment by stefanhorning** [comment]
Replaced by https://github.com/mediapeers/postjob/pull/12

**Pull request closed without merging**
